language: python
python:
- '3.6'
cache: pip3
install:
- pip3 install pytest
script:
- pytest -v test-basic-calc.py
notifications:
  slack: personal-ctr2253:QEmplOTHFd34azsXQzzKzAub
  on_success: always
  on_failure: always