language: python
python:
- '3.6'
cache: pip3
install:
- pip3 install pytest
script:
- pytest -v test-basic-calc.py
notifications:
  slack: 
    rooms:
      - secure: secure: "RqaZI3p38Y9VnArqUj4LLKBnM0e5OBWVQ+BUtVdcj9c4IdG09hJOaV/330lxqst4fjcUpqbr6CGeEXLBwLp8RSxt5iQCaGbCB2t8eteMHyh5nkVseQn4/hqQ/Y73TOBct6e7nl4zqock4CVMJSDE3Vo6z/YIesQaSfhD3g1m8YAvTY+ogiROsuAXb7A/K+AuDx/VTrFWNwf607Doo+d4d2yrqg266S4qAmsafO8DQDLgbWT7NTGGZMHqkSso9A7XFyI1Nmh/U77szbDKCtZozDfEkgw6/E5teMjmgFrRfkQKJ9LMixBAaqTPVj1lKXXHQbYYtKSC/eCR6XvkxNij2K/x6TgFRJJakCFoNRB4ptuse7+/5NNykk9GM4eqC2wNXKmpyDWCy+XmGi/RoHgg1gy83faRcf3/ZJQWi+bPE6CugclVxcXTJbtsE/IJj4hs3QMTtxZ8qHapuZXJAiTBoI5DdYJcRvh0/Jv7ljaDzT5dESAS5njot4r63vOQsyxAhxQxVwXH1w/rih1QiOxv5qhOItao+IJ33J/iyUdDZ1RksMS0POgKD+TEZkCkbiUvXXh1N/NC1HtAmm8LQZfTOiSjIaMCGVgwD3jp7/3uThhlcyDyIAjWijy0j28Q3GDJpgSJY82/RYiaSSHULBOmc26aMILiso2I9VCMEMH7ZmU="
    on_success: always
    on_failure: always