language: python
python:
  - "3.6"
cache: pip3
install:
  - pip3 install pytest
script:
  - pytest -v test-basic-calc.py
notifications:
  #slack: personal-ctr2253:1
  secure: "e2CXqLXRiITMXMwSJQ774/M5yiy6ozrSNrSo5PhJHYvc+z1PlHl+lREsEcbgjhcBLFqP3GylJjG/hKmB4S/gujrMLFS00KXqQbA8UPVaELt11aRmOGtXpZd+2Q4/aU6c+hy+/tsZxoMrk19GgDPJ6dB48Fikix8l/EhM1T/DG+Wobp6NFGpFtAV5YvCGp2mby3BTu14R4CHQMMLaxlgWsoLtsm2dO8iQmH7lo79+c9txNYijrCA+IS5dYj49P3D1URxOXPRy7pancjTLSrHSeK0KNYfnTN7LvhkAXSU1ZEfWvpAEztF4AggYGNCOafS0QVrVX4Vjj/W5djoH7ytSc6e36RDF028ZHBXzTLkDnKdkS2NT+KLcI1aQ6s23mo0OEi6kFdC/EmkniSWUz6uMsouAPLvT8tdzqSd9FUthIShKsgMOktEoOG0TncfQ1NSuo4VLswhnb1uton5a7dGU7jY/aj0nw8jNwWek4Q1bH8F1JV7OBnYsTDIpvY2/1ZgLjyJuaIi1J07Xnvz+VNsdRLC5Ist9Eu31pbIXTQLaXZLxhYfOPInRX3qih/jsVKlViVT2GcDiC8OeFEP/LOsrCUgqQrLNLbTQCKefVsixDpcsZUwn+1iqTrb2jbonLmbbT6uBWavrOyGPhAzBInFe3atPAibSMyabJ8dzw5aqIwA="
  on_success: always
  on_failure: always